# Generated by Django 3.2.9 on 2021-11-29 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0008_alter_person_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('client_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_secret', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
            ],
        ),
    ]
