# Generated by Django 4.0.2 on 2022-02-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keys',
            old_name='person',
            new_name='account',
        ),
    ]
