# Generated by Django 4.0.2 on 2022-02-17 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_person_keys_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keys',
        ),
    ]
