# Generated by Django 3.2.9 on 2021-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20211129_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
