# Generated by Django 3.2.9 on 2021-12-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_keys_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='creation_time',
        ),
    ]
