# Generated by Django 4.0.2 on 2022-02-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_person_account'),
        ('API', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttoken',
            options={},
        ),
        migrations.AlterField(
            model_name='accounttoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='accounts.account', verbose_name='User'),
        ),
    ]
