# Generated by Django 4.0.2 on 2022-02-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_accounttoken_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountToken',
        ),
    ]
