# Generated by Django 3.2.9 on 2021-12-04 00:59

import django.core.validators
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('net_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('allergens', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='contents',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
    ]
