# Generated by Django 3.2.9 on 2021-12-06 09:14

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20211206_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='contents',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
    ]
