# Generated by Django 3.2.9 on 2021-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_package_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
