# Generated by Django 4.0 on 2022-01-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_package_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_liquid',
            field=models.BooleanField(default=False),
        ),
    ]
