# Generated by Django 4.0 on 2022-01-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_products_is_liquid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
