# Generated by Django 4.0.2 on 2022-02-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
