# Generated by Django 4.0.2 on 2022-02-23 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_alter_package_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.status'),
        ),
    ]
