# Generated by Django 4.0.2 on 2022-02-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_status_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
    ]
