# Generated by Django 4.0.2 on 2022-02-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_remove_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.status'),
        ),
    ]
