# Generated by Django 3.2.9 on 2021-11-01 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999),
                                                                django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5,
                                               validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999),
                                                                   django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
