# Generated by Django 4.0.2 on 2022-02-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_rename_products_product'),
        ('API', '0002_rename_person_keys_account'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Account',
        ),
    ]
