# Generated by Django 3.2.9 on 2021-11-06 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20211106_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5,
                                      validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
