# Generated by Django 3.2.9 on 2021-11-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_alter_person_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='login',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
